/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge { 'name' : string, 'description' : string }
export interface EducationArticle {
  'title' : string,
  'content' : string,
  'summary' : string,
}
export type MarketMode = { 'normal' : null } |
  { 'bear' : null } |
  { 'bull' : null };
export type Time = bigint;
export interface Trade {
  'totalValue' : number,
  'coin' : string,
  'side' : TradeSide,
  'timestamp' : Time,
  'quantity' : number,
  'price' : number,
}
export type TradeSide = { 'buy' : null } |
  { 'sell' : null };
export interface TutorLesson {
  'id' : string,
  'question' : string,
  'tips' : Array<string>,
  'answer' : string,
  'category' : string,
}
export interface UserDataView {
  'xp' : bigint,
  'portfolio' : Array<{ 'coin' : string, 'quantity' : number }>,
  'balance' : number,
  'tradeHistory' : Array<Trade>,
  'badges' : Array<Badge>,
}
export interface _SERVICE {
  'buy' : ActorMethod<[string, number], undefined>,
  'getAcademyContent' : ActorMethod<[], Array<EducationArticle>>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, UserDataView]>>,
  'getMarketMode' : ActorMethod<[], MarketMode>,
  'getOrCreateUserData' : ActorMethod<[], UserDataView>,
  'getTutorLessons' : ActorMethod<[], Array<TutorLesson>>,
  'sell' : ActorMethod<[string, number], undefined>,
  'setMarketMode' : ActorMethod<[MarketMode], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];