/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EducationArticle = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'summary' : IDL.Text,
});
export const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Time = IDL.Int;
export const Trade = IDL.Record({
  'totalValue' : IDL.Float64,
  'coin' : IDL.Text,
  'side' : TradeSide,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
});
export const Badge = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserDataView = IDL.Record({
  'xp' : IDL.Nat,
  'portfolio' : IDL.Vec(
    IDL.Record({ 'coin' : IDL.Text, 'quantity' : IDL.Float64 })
  ),
  'balance' : IDL.Float64,
  'tradeHistory' : IDL.Vec(Trade),
  'badges' : IDL.Vec(Badge),
});
export const MarketMode = IDL.Variant({
  'normal' : IDL.Null,
  'bear' : IDL.Null,
  'bull' : IDL.Null,
});
export const TutorLesson = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'tips' : IDL.Vec(IDL.Text),
  'answer' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'buy' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'getAcademyContent' : IDL.Func([], [IDL.Vec(EducationArticle)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserDataView))],
      ['query'],
    ),
  'getMarketMode' : IDL.Func([], [MarketMode], ['query']),
  'getOrCreateUserData' : IDL.Func([], [UserDataView], []),
  'getTutorLessons' : IDL.Func([], [IDL.Vec(TutorLesson)], ['query']),
  'sell' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'setMarketMode' : IDL.Func([MarketMode], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EducationArticle = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'summary' : IDL.Text,
  });
  const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Time = IDL.Int;
  const Trade = IDL.Record({
    'totalValue' : IDL.Float64,
    'coin' : IDL.Text,
    'side' : TradeSide,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const Badge = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const UserDataView = IDL.Record({
    'xp' : IDL.Nat,
    'portfolio' : IDL.Vec(
      IDL.Record({ 'coin' : IDL.Text, 'quantity' : IDL.Float64 })
    ),
    'balance' : IDL.Float64,
    'tradeHistory' : IDL.Vec(Trade),
    'badges' : IDL.Vec(Badge),
  });
  const MarketMode = IDL.Variant({
    'normal' : IDL.Null,
    'bear' : IDL.Null,
    'bull' : IDL.Null,
  });
  const TutorLesson = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'tips' : IDL.Vec(IDL.Text),
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'buy' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getAcademyContent' : IDL.Func([], [IDL.Vec(EducationArticle)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserDataView))],
        ['query'],
      ),
    'getMarketMode' : IDL.Func([], [MarketMode], ['query']),
    'getOrCreateUserData' : IDL.Func([], [UserDataView], []),
    'getTutorLessons' : IDL.Func([], [IDL.Vec(TutorLesson)], ['query']),
    'sell' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'setMarketMode' : IDL.Func([MarketMode], [], []),
  });
};

export const init = ({ IDL }) => { return []; };