/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface EducationArticle {
    title: string;
    content: string;
    summary: string;
}
export interface Trade {
    totalValue: number;
    coin: string;
    side: TradeSide;
    timestamp: Time;
    quantity: number;
    price: number;
}
export interface UserDataView {
    xp: bigint;
    portfolio: {
        coin: string;
        quantity: number;
    };
    balance: number;
    tradeHistory: Array<Trade>;
    badges: Array<Badge>;
}
export interface Badge {
    name: string;
    description: string;
}
export enum MarketMode {
    normal = "normal",
    bear = "bear",
    bull = "bull"
}
export enum TradeSide {
    buy = "buy",
    sell = "sell"
}
export interface backendInterface {
    buy(coin: string, usdAmount: number): Promise<void>;
    getAcademyContent(): Promise<Array<EducationArticle>>;
    getLeaderboard(): Promise<Array<[Principal, UserDataView]>>;
    getMarketMode(): Promise<MarketMode>;
    getOrCreateUserData(): Promise<UserDataView>;
    sell(coin: string, quantity: number): Promise<void>;
    setMarketMode(mode: MarketMode): Promise<void>;
}
import type { Badge as _Badge, MarketMode as _MarketMode, Time as _Time, Trade as _Trade, TradeSide as _TradeSide, UserDataView as _UserDataView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async buy(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.buy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buy(arg0, arg1);
            return result;
        }
    }
    async getAcademyContent(): Promise<Array<EducationArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademyContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademyContent();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<[Principal, UserDataView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketMode(): Promise<MarketMode> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketMode();
                return from_candid_MarketMode_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketMode();
            return from_candid_MarketMode_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateUserData(): Promise<UserDataView> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateUserData();
                return from_candid_UserDataView_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateUserData();
            return from_candid_UserDataView_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async sell(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sell(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sell(arg0, arg1);
            return result;
        }
    }
    async setMarketMode(arg0: MarketMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMarketMode(to_candid_MarketMode_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMarketMode(to_candid_MarketMode_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_MarketMode_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketMode): MarketMode {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TradeSide_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeSide): TradeSide {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserDataView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDataView): UserDataView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    portfolio: {
        coin: string;
        quantity: number;
    };
    balance: number;
    tradeHistory: Array<_Trade>;
    badges: Array<_Badge>;
}): {
    xp: bigint;
    portfolio: {
        coin: string;
        quantity: number;
    };
    balance: number;
    tradeHistory: Array<Trade>;
    badges: Array<Badge>;
} {
    return {
        xp: value.xp,
        portfolio: value.portfolio,
        balance: value.balance,
        tradeHistory: from_candid_vec_n5(_uploadFile, _downloadFile, value.tradeHistory),
        badges: value.badges
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValue: number;
    coin: string;
    side: _TradeSide;
    timestamp: _Time;
    quantity: number;
    price: number;
}): {
    totalValue: number;
    coin: string;
    side: TradeSide;
    timestamp: Time;
    quantity: number;
    price: number;
} {
    return {
        totalValue: value.totalValue,
        coin: value.coin,
        side: from_candid_TradeSide_n8(_uploadFile, _downloadFile, value.side),
        timestamp: value.timestamp,
        quantity: value.quantity,
        price: value.price
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserDataView]): [Principal, UserDataView] {
    return [
        value[0],
        from_candid_UserDataView_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    bear: null;
} | {
    bull: null;
}): MarketMode {
    return "normal" in value ? MarketMode.normal : "bear" in value ? MarketMode.bear : "bull" in value ? MarketMode.bull : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeSide {
    return "buy" in value ? TradeSide.buy : "sell" in value ? TradeSide.sell : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserDataView]>): Array<[Principal, UserDataView]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MarketMode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketMode): _MarketMode {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketMode): {
    normal: null;
} | {
    bear: null;
} | {
    bull: null;
} {
    return value == MarketMode.normal ? {
        normal: null
    } : value == MarketMode.bear ? {
        bear: null
    } : value == MarketMode.bull ? {
        bull: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
